# Generated by Django 5.0.2 on 2024-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addis', '0002_rename_location_user_email_remove_user_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, upload_to='portifolo_images/'),
        ),
    ]
